### ISSUE TITLE
feat(CO2): footprint calculation

### ISSUE THREAD

**Issue by tzsombi01** [Project-PackX/backend#13]

**Comment by MrHumanRebel** [comment]
Required for sum all packages together for homapage, and also per package CO2 savings.

**Comment by tzsombi01** [comment]
@MrHumanRebel  @arturfriedrich  You can find the endpoint on: GET /api/emissions -> Unauthorized endpoint
Response: IN BODY (JSON) 
Example
{
	"All": 144.35831599802646,
	"EmissionPerPackage": 10.311308285573318
}

Will write a FE ticket as well, when you add a locker, we need Latitude, and Longitude, I added them for the default lockers by hand. 
I added a Co2 field to the Package class. When adding a package, you do not need to send it, I will fill it on the backend. But you need to display it on the FE if the user e.g. looks at his packages.
