### ISSUE TITLE
(history): delivery date 

### ISSUE THREAD

**Issue by arturfriedrich** [Project-PackX/backend#14]
delivery date same as created at
<img width="551" alt="image" src="https://github.com/Project-PackX/backend/assets/67378210/8e81ff51-d048-4eff-a2ee-0e5211c79a15">

**Comment by arturfriedrich** [comment]
eküldöm a feladásnál a dátumot, csináld meg hogy fogadni tudja

**Comment by tzsombi01** [comment]
@arturfriedrich  Ennek mennie kéne, "deliveryDate"  vagy "DeliveryDate" a kulcs, és egy string: "2023-11-12T12:11:20.9819034+01:00" pl
