### ISSUE TITLE
fix(email): Sender-receiver name, ID Field

### ISSUE THREAD

**Issue by MrHumanRebel** [Project-PackX/backend#16]
General: 
Sender and receiver name not showing correctly in an email. 

Additionally package status change email, ID field not working.

![image](https://github.com/Project-PackX/backend/assets/80947401/18ae8b16-efbb-4b87-be34-dd64c26cb844)

**Comment by tzsombi01** [comment]
@MrHumanRebel Teszteld légyszi, javítva
