### ISSUE TITLE
fix(locker-capacity): do not allow overflow

### ISSUE THREAD

**Issue by MrHumanRebel** [Project-PackX/backend#20]
![image](https://github.com/Project-PackX/backend/assets/80947401/b4ecee4b-e6e0-4a2d-9b8f-fa25b1c4053c)

If a locker is full forbid sending more packages to given locker, respond with locker-full error, what can be displayed on frontend.

**Comment by tzsombi01** [comment]
@MrHumanRebel Teszteld légyszi, javítva, nem fog engedni feladni több csomagot, ha fullon van. A meglévők közül cancelelj párat, és fullos lesz onnantól :)
